CREATE TABLE [dbo].[Contenido] (
    [Id_Producto]               REAL           NOT NULL,
    [Nombre_Producto]           NCHAR (30)     NOT NULL,
    [Descripción]               NCHAR (200)    NOT NULL,
    [Cod_Producto]              REAL           NOT NULL,
    [Marca]                     NCHAR (15)     NOT NULL,
    [Img_Producto]              NCHAR (10)     NOT NULL,
    [Precio_Venta]              REAL           NOT NULL,
    [Numero_Venta]              INT            NOT NULL,
    [Cantidad_De_Venta]         INT            NOT NULL,
    [Cantidad_Producto]         INT            NOT NULL,
    [Fecha_Venta]               DATE           NOT NULL,
    [Cantidad_Producto_Vendido] INT            NOT NULL,
    [Precio_Total]              REAL           NOT NULL,
    [Inventario]                NVARCHAR (MAX) NOT NULL,
    [Id_Cliente]                REAL           NOT NULL,
    [Nombre_Cliente]            NCHAR (25)     NOT NULL,
    [Direcciòn]                 NTEXT          NOT NULL,
    [Sexo]                      NCHAR (10)     NOT NULL,
    [E-Mail]                    NVARCHAR (50)  NOT NULL,
    [Departamento]              NVARCHAR (50)  NOT NULL,
    [Municipio]                 NVARCHAR (50)  NOT NULL,
    [Id_Empleado]               REAL           NOT NULL,
    [Nombre_Empleado]           NCHAR (25)     NOT NULL,
    [Cedula]                    INT            NOT NULL,
    [Categoria]                 NVARCHAR (50)  NOT NULL,
    [Id_Proveedor]              REAL           NOT NULL,
    [Compañia_Proveedora]       NCHAR (10)     NOT NULL,
    [Cant_Compra_Provee]        INT            NOT NULL,
    [Fecha_Compra_Provee]       DATE           NOT NULL,
    [Factura_Producto]          NVARCHAR (MAX) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id_Producto] ASC)
);

